# -*- coding: utf-8 -*-
"""fantasy_engine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TMoavrg6TD1o8Z_W0Thhu6ebTBSh1fDF
"""

import random

def draft_phase(df, difficulty, draft_model):
  player_team = []
  ai_team = []

  # Create a copy of the dataframe for the draft pool and add 'is_drafted' column
  draftable_players = df.copy()
  draftable_players['is_drafted'] = False

  # Define total draft rounds (5 players per team = 10 picks)
  total_picks = 10

  print("\n--- Draft Phase Begins ---")

  # ---- New Logic: Determine First Pick with Rock-Paper-Scissors ----
  print("\n--- Determining First Pick: Rock-Paper-Scissors ---")
  player_gets_first_pick = False
  while True:
    player_choice = input("Choose your weapon (rock, paper, scissors): ").lower()
    if player_choice not in ['rock', 'paper', 'scissors']:
      print("Invalid choice. Please choose 'rock', 'paper', or 'scissors'.")
      continue

    ai_choice = random.choice(['rock', 'paper', 'scissors'])
    print(f"Player chose: {player_choice}")
    print(f"AI chose: {ai_choice}")

    if player_choice == ai_choice:
      print("It's a tie! Let's play again.")
    elif (player_choice == 'rock' and ai_choice == 'scissors') or \
         (player_choice == 'paper' and ai_choice == 'rock') or \
         (player_choice == 'scissors' and ai_choice == 'paper'):
      print("Player wins the first pick!")
      player_gets_first_pick = True
      break
    else:
      print("AI wins the first pick!")
      player_gets_first_pick = False
      break
  print("---------------------------------------------------")

  for pick_num in range(total_picks):
    print(f"\nPick {pick_num + 1}/{total_picks}")

    # Determine the current snake round number (0-indexed: 0, 1, 2, 3, 4)
    snake_round_number = pick_num // 2

    is_player_picking_now = False
    if player_gets_first_pick:
      if snake_round_number % 2 == 0: # Forward round (Player -> AI)
        is_player_picking_now = (pick_num % 2 == 0)
      else: # Reverse round (AI -> Player)
        is_player_picking_now = (pick_num % 2 != 0)
    else: # AI gets first pick
      if snake_round_number % 2 == 0: # Forward round (AI -> Player)
        is_player_picking_now = (pick_num % 2 != 0)
      else: # Reverse round (Player -> AI)
        is_player_picking_now = (pick_num % 2 == 0)

    if is_player_picking_now:
      print("Player's turn to pick...")
      # 1. Display available players
      available_players = draftable_players[draftable_players['is_drafted'] == False]
      print("\nAvailable Players:")
      # Display only relevant columns for player choice
      print(available_players[['player_id', 'Player', 'pred_score']].sort_values(by='pred_score', ascending=False).to_string(index=False))

      player_selected_id = -1
      while True:
        try:
          # 2. Prompt for input
          player_input = input("Enter the player_id of your desired pick: ")
          player_selected_id = int(player_input)

          # 3a. Check if input is a valid integer (handled by try-except)
          # 3b. Check if player_id exists in draftable_players
          if player_selected_id not in draftable_players['player_id'].values:
            print("Invalid player_id. Please enter an existing player_id.")
            continue

          # 3c. Check if the chosen player is already drafted
          if draftable_players.loc[draftable_players['player_id'] == player_selected_id, 'is_drafted'].iloc[0]:
            print(f"Player with ID {player_selected_id} is already drafted. Choose another player.")
            continue

          # If all checks pass, break the loop
          break

        except ValueError:
          print("Invalid input. Please enter a valid integer for player_id.")
        except IndexError: # Should not happen if player_id in values check works, but good for robustness
            print("Player ID not found. Please try again.")

      # 4. Add to player_team
      player_team.append(player_selected_id)
      # 5. Mark as drafted
      draftable_players.loc[draftable_players['player_id'] == player_selected_id, 'is_drafted'] = True
      print(f"Player {draftable_players.loc[draftable_players['player_id'] == player_selected_id, 'Player'].iloc[0]} (ID: {player_selected_id}) drafted by Player.")

    else: # AI picks
      print("AI's turn to pick...")
      available_for_ai = draftable_players[draftable_players['is_drafted'] == False]

      ai_selected_id = None
      if difficulty == "easy":
        ai_selected_id = ai_pick_easy(available_for_ai)
      elif difficulty == "medium":
        ai_selected_id = ai_pick_medium(available_for_ai, draft_model)
      elif difficulty == "hard":
        ai_selected_id = ai_pick_hard(available_for_ai, draft_model)
      else: # Default to easy if difficulty is not recognized or model is None for medium/hard
          ai_selected_id = ai_pick_easy(available_for_ai)

      ai_team.append(ai_selected_id)
      draftable_players.loc[draftable_players['player_id'] == ai_selected_id, 'is_drafted'] = True
      print(f"AI drafted player {draftable_players.loc[draftable_players['player_id'] == ai_selected_id, 'Player'].iloc[0]} (ID: {ai_selected_id}).")


  print("\n--- Draft Phase Ends ---")
  return player_team, ai_team

def simulate_match(player_team, ai_team, df):
  player_score = sum(df.loc[i, "pred_score"] for i in player_team)
  ai_score = sum(df.loc[i, "pred_score"] for i in ai_team)
  if player_score > ai_score:
    winner = "Player"
  elif player_score < ai_score:
    winner = "AI"
  else:
    winner = "Draw"
  return {"player_score": player_score, "ai_score": ai_score, "winner": winner}